#ifndef MCMT_TOKEN_COMPARE_H
#define MCMT_TOKEN_COMPARE_H

/* MCMT_TOKEN_COMPARE_TEMPLATES_FOR_LOGIC */

#define COMPARE__(_x) _x

#define COMPARE_a(_x) _x
#define COMPARE_b(_x) _x
#define COMPARE_c(_x) _x
#define COMPARE_d(_x) _x
#define COMPARE_e(_x) _x
#define COMPARE_f(_x) _x
#define COMPARE_g(_x) _x
#define COMPARE_h(_x) _x
#define COMPARE_i(_x) _x
#define COMPARE_j(_x) _x
#define COMPARE_k(_x) _x
#define COMPARE_l(_x) _x
#define COMPARE_m(_x) _x
#define COMPARE_n(_x) _x
#define COMPARE_o(_x) _x
#define COMPARE_p(_x) _x
#define COMPARE_q(_x) _x
#define COMPARE_r(_x) _x
#define COMPARE_s(_x) _x
#define COMPARE_t(_x) _x
#define COMPARE_u(_x) _x
#define COMPARE_v(_x) _x
#define COMPARE_w(_x) _x
#define COMPARE_x(_x) _x
#define COMPARE_y(_x) _x
#define COMPARE_z(_x) _x

#define COMPARE_A(_x) _x
#define COMPARE_B(_x) _x
#define COMPARE_C(_x) _x
#define COMPARE_D(_x) _x
#define COMPARE_E(_x) _x
#define COMPARE_F(_x) _x
#define COMPARE_G(_x) _x
#define COMPARE_H(_x) _x
#define COMPARE_I(_x) _x
#define COMPARE_J(_x) _x
#define COMPARE_K(_x) _x
#define COMPARE_L(_x) _x
#define COMPARE_M(_x) _x
#define COMPARE_N(_x) _x
#define COMPARE_O(_x) _x
#define COMPARE_P(_x) _x
#define COMPARE_Q(_x) _x
#define COMPARE_R(_x) _x
#define COMPARE_S(_x) _x
#define COMPARE_T(_x) _x
#define COMPARE_U(_x) _x
#define COMPARE_V(_x) _x
#define COMPARE_W(_x) _x
#define COMPARE_X(_x) _x
#define COMPARE_Y(_x) _x
#define COMPARE_Z(_x) _x

#define COMPARE_asm(_x)              _x
#define COMPARE_and(_x)              _x
#define COMPARE_and_eq(_x)           _x
#define COMPARE_auto(_x)             _x
#define COMPARE_bitand(_x)           _x
#define COMPARE_bitor(_x)            _x
#define COMPARE_bool(_x)             _x
#define COMPARE_break(_x)            _x
#define COMPARE_case(_x)             _x
#define COMPARE_catch(_x)            _x
#define COMPARE_char(_x)             _x
#define COMPARE_class(_x)            _x
#define COMPARE_compl(_x)            _x
#define COMPARE_const(_x)            _x
#define COMPARE_const_cast(_x)       _x
#define COMPARE_continue(_x)         _x
#define COMPARE_default(_x)          _x
#define COMPARE_define(_x)           _x
#define COMPARE_defined(_x)          _x
#define COMPARE_delete(_x)           _x
#define COMPARE_do(_x)               _x
#define COMPARE_double(_x)           _x
#define COMPARE_dynamic_cast(_x)     _x
#define COMPARE_else(_x)             _x
#define COMPARE_elif(_x)             _x
#define COMPARE_endif(_x)            _x
#define COMPARE_enum(_x)             _x
#define COMPARE_error(_x)            _x
#define COMPARE_explicit(_x)         _x
#define COMPARE_export(_x)           _x
#define COMPARE_extern(_x)           _x
#define COMPARE_false(_x)            _x
#define COMPARE_float(_x)            _x
#define COMPARE_for(_x)              _x
#define COMPARE_friend(_x)           _x
#define COMPARE_goto(_x)             _x
#define COMPARE_if(_x)               _x
#define COMPARE_ifdef(_x)            _x
#define COMPARE_ifndef(_x)           _x
#define COMPARE_include(_x)          _x
#define COMPARE_inline(_x)           _x
#define COMPARE_int(_x)              _x
#define COMPARE_line(_x)             _x
#define COMPARE_long(_x)             _x
#define COMPARE_mutable(_x)          _x
#define COMPARE_namespace(_x)        _x
#define COMPARE_new(_x)              _x
#define COMPARE_not(_x)              _x
#define COMPARE_not_eq(_x)           _x
#define COMPARE_operator(_x)         _x
#define COMPARE_or(_x)               _x
#define COMPARE_or_eq(_x)            _x
#define COMPARE_pragma(_x)           _x
#define COMPARE_private(_x)          _x
#define COMPARE_protected(_x)        _x
#define COMPARE_public(_x)           _x
#define COMPARE_register(_x)         _x
#define COMPARE_reinterpret_cast(_x) _x
#define COMPARE_restrict(_x)         _x
#define COMPARE_return(_x)           _x
#define COMPARE_short(_x)            _x
#define COMPARE_signed(_x)           _x
#define COMPARE_sizeof(_x)           _x
#define COMPARE_static(_x)           _x
#define COMPARE_static_cast(_x)      _x
#define COMPARE_struct(_x)           _x
#define COMPARE_switch(_x)           _x
#define COMPARE_template(_x)         _x
#define COMPARE_this(_x)             _x
#define COMPARE_throw(_x)            _x
#define COMPARE_true(_x)             _x
#define COMPARE_try(_x)              _x
#define COMPARE_typedef(_x)          _x
#define COMPARE_typeid(_x)           _x
#define COMPARE_typename(_x)         _x
#define COMPARE_undef(_x)            _x
#define COMPARE_union(_x)            _x
#define COMPARE_unsigned(_x)         _x
#define COMPARE_using(_x)            _x
#define COMPARE_virtual(_x)          _x
#define COMPARE_void(_x)             _x
#define COMPARE_volatile(_x)         _x
#define COMPARE_wchar_t(_x)          _x
#define COMPARE_while(_x)            _x
#define COMPARE_xor(_x)              _x
#define COMPARE_xor_eq(_x)           _x

#define COMPARE_0(_x)   _x
#define COMPARE_1(_x)   _x
#define COMPARE_2(_x)   _x
#define COMPARE_3(_x)   _x
#define COMPARE_4(_x)   _x
#define COMPARE_5(_x)   _x
#define COMPARE_6(_x)   _x
#define COMPARE_7(_x)   _x
#define COMPARE_8(_x)   _x
#define COMPARE_9(_x)   _x
#define COMPARE_10(_x)  _x
#define COMPARE_11(_x)  _x
#define COMPARE_12(_x)  _x
#define COMPARE_13(_x)  _x
#define COMPARE_14(_x)  _x
#define COMPARE_15(_x)  _x
#define COMPARE_16(_x)  _x
#define COMPARE_17(_x)  _x
#define COMPARE_18(_x)  _x
#define COMPARE_19(_x)  _x
#define COMPARE_20(_x)  _x
#define COMPARE_21(_x)  _x
#define COMPARE_22(_x)  _x
#define COMPARE_23(_x)  _x
#define COMPARE_24(_x)  _x
#define COMPARE_25(_x)  _x
#define COMPARE_26(_x)  _x
#define COMPARE_27(_x)  _x
#define COMPARE_28(_x)  _x
#define COMPARE_29(_x)  _x
#define COMPARE_30(_x)  _x
#define COMPARE_31(_x)  _x
#define COMPARE_32(_x)  _x
#define COMPARE_33(_x)  _x
#define COMPARE_34(_x)  _x
#define COMPARE_35(_x)  _x
#define COMPARE_36(_x)  _x
#define COMPARE_37(_x)  _x
#define COMPARE_38(_x)  _x
#define COMPARE_39(_x)  _x
#define COMPARE_40(_x)  _x
#define COMPARE_41(_x)  _x
#define COMPARE_42(_x)  _x
#define COMPARE_43(_x)  _x
#define COMPARE_44(_x)  _x
#define COMPARE_45(_x)  _x
#define COMPARE_46(_x)  _x
#define COMPARE_47(_x)  _x
#define COMPARE_48(_x)  _x
#define COMPARE_49(_x)  _x
#define COMPARE_50(_x)  _x
#define COMPARE_51(_x)  _x
#define COMPARE_52(_x)  _x
#define COMPARE_53(_x)  _x
#define COMPARE_54(_x)  _x
#define COMPARE_55(_x)  _x
#define COMPARE_56(_x)  _x
#define COMPARE_57(_x)  _x
#define COMPARE_58(_x)  _x
#define COMPARE_59(_x)  _x
#define COMPARE_60(_x)  _x
#define COMPARE_61(_x)  _x
#define COMPARE_62(_x)  _x
#define COMPARE_63(_x)  _x
#define COMPARE_64(_x)  _x
#define COMPARE_65(_x)  _x
#define COMPARE_66(_x)  _x
#define COMPARE_67(_x)  _x
#define COMPARE_68(_x)  _x
#define COMPARE_69(_x)  _x
#define COMPARE_70(_x)  _x
#define COMPARE_71(_x)  _x
#define COMPARE_72(_x)  _x
#define COMPARE_73(_x)  _x
#define COMPARE_74(_x)  _x
#define COMPARE_75(_x)  _x
#define COMPARE_76(_x)  _x
#define COMPARE_77(_x)  _x
#define COMPARE_78(_x)  _x
#define COMPARE_79(_x)  _x
#define COMPARE_80(_x)  _x
#define COMPARE_81(_x)  _x
#define COMPARE_82(_x)  _x
#define COMPARE_83(_x)  _x
#define COMPARE_84(_x)  _x
#define COMPARE_85(_x)  _x
#define COMPARE_86(_x)  _x
#define COMPARE_87(_x)  _x
#define COMPARE_88(_x)  _x
#define COMPARE_89(_x)  _x
#define COMPARE_90(_x)  _x
#define COMPARE_91(_x)  _x
#define COMPARE_92(_x)  _x
#define COMPARE_93(_x)  _x
#define COMPARE_94(_x)  _x
#define COMPARE_95(_x)  _x
#define COMPARE_96(_x)  _x
#define COMPARE_97(_x)  _x
#define COMPARE_98(_x)  _x
#define COMPARE_99(_x)  _x
#define COMPARE_100(_x) _x
#define COMPARE_101(_x) _x
#define COMPARE_102(_x) _x
#define COMPARE_103(_x) _x
#define COMPARE_104(_x) _x
#define COMPARE_105(_x) _x
#define COMPARE_106(_x) _x
#define COMPARE_107(_x) _x
#define COMPARE_108(_x) _x
#define COMPARE_109(_x) _x
#define COMPARE_110(_x) _x
#define COMPARE_111(_x) _x
#define COMPARE_112(_x) _x
#define COMPARE_113(_x) _x
#define COMPARE_114(_x) _x
#define COMPARE_115(_x) _x
#define COMPARE_116(_x) _x
#define COMPARE_117(_x) _x
#define COMPARE_118(_x) _x
#define COMPARE_119(_x) _x
#define COMPARE_120(_x) _x
#define COMPARE_121(_x) _x
#define COMPARE_122(_x) _x
#define COMPARE_123(_x) _x
#define COMPARE_124(_x) _x
#define COMPARE_125(_x) _x
#define COMPARE_126(_x) _x
#define COMPARE_127(_x) _x
#define COMPARE_128(_x) _x
#define COMPARE_129(_x) _x
#define COMPARE_130(_x) _x
#define COMPARE_131(_x) _x
#define COMPARE_132(_x) _x
#define COMPARE_133(_x) _x
#define COMPARE_134(_x) _x
#define COMPARE_135(_x) _x
#define COMPARE_136(_x) _x
#define COMPARE_137(_x) _x
#define COMPARE_138(_x) _x
#define COMPARE_139(_x) _x
#define COMPARE_140(_x) _x
#define COMPARE_141(_x) _x
#define COMPARE_142(_x) _x
#define COMPARE_143(_x) _x
#define COMPARE_144(_x) _x
#define COMPARE_145(_x) _x
#define COMPARE_146(_x) _x
#define COMPARE_147(_x) _x
#define COMPARE_148(_x) _x
#define COMPARE_149(_x) _x
#define COMPARE_150(_x) _x
#define COMPARE_151(_x) _x
#define COMPARE_152(_x) _x
#define COMPARE_153(_x) _x
#define COMPARE_154(_x) _x
#define COMPARE_155(_x) _x
#define COMPARE_156(_x) _x
#define COMPARE_157(_x) _x
#define COMPARE_158(_x) _x
#define COMPARE_159(_x) _x
#define COMPARE_160(_x) _x
#define COMPARE_161(_x) _x
#define COMPARE_162(_x) _x
#define COMPARE_163(_x) _x
#define COMPARE_164(_x) _x
#define COMPARE_165(_x) _x
#define COMPARE_166(_x) _x
#define COMPARE_167(_x) _x
#define COMPARE_168(_x) _x
#define COMPARE_169(_x) _x
#define COMPARE_170(_x) _x
#define COMPARE_171(_x) _x
#define COMPARE_172(_x) _x
#define COMPARE_173(_x) _x
#define COMPARE_174(_x) _x
#define COMPARE_175(_x) _x
#define COMPARE_176(_x) _x
#define COMPARE_177(_x) _x
#define COMPARE_178(_x) _x
#define COMPARE_179(_x) _x
#define COMPARE_180(_x) _x
#define COMPARE_181(_x) _x
#define COMPARE_182(_x) _x
#define COMPARE_183(_x) _x
#define COMPARE_184(_x) _x
#define COMPARE_185(_x) _x
#define COMPARE_186(_x) _x
#define COMPARE_187(_x) _x
#define COMPARE_188(_x) _x
#define COMPARE_189(_x) _x
#define COMPARE_190(_x) _x
#define COMPARE_191(_x) _x
#define COMPARE_192(_x) _x
#define COMPARE_193(_x) _x
#define COMPARE_194(_x) _x
#define COMPARE_195(_x) _x
#define COMPARE_196(_x) _x
#define COMPARE_197(_x) _x
#define COMPARE_198(_x) _x
#define COMPARE_199(_x) _x
#define COMPARE_200(_x) _x
#define COMPARE_201(_x) _x
#define COMPARE_202(_x) _x
#define COMPARE_203(_x) _x
#define COMPARE_204(_x) _x
#define COMPARE_205(_x) _x
#define COMPARE_206(_x) _x
#define COMPARE_207(_x) _x
#define COMPARE_208(_x) _x
#define COMPARE_209(_x) _x
#define COMPARE_210(_x) _x
#define COMPARE_211(_x) _x
#define COMPARE_212(_x) _x
#define COMPARE_213(_x) _x
#define COMPARE_214(_x) _x
#define COMPARE_215(_x) _x
#define COMPARE_216(_x) _x
#define COMPARE_217(_x) _x
#define COMPARE_218(_x) _x
#define COMPARE_219(_x) _x
#define COMPARE_220(_x) _x
#define COMPARE_221(_x) _x
#define COMPARE_222(_x) _x
#define COMPARE_223(_x) _x
#define COMPARE_224(_x) _x
#define COMPARE_225(_x) _x
#define COMPARE_226(_x) _x
#define COMPARE_227(_x) _x
#define COMPARE_228(_x) _x
#define COMPARE_229(_x) _x
#define COMPARE_230(_x) _x
#define COMPARE_231(_x) _x
#define COMPARE_232(_x) _x
#define COMPARE_233(_x) _x
#define COMPARE_234(_x) _x
#define COMPARE_235(_x) _x
#define COMPARE_236(_x) _x
#define COMPARE_237(_x) _x
#define COMPARE_238(_x) _x
#define COMPARE_239(_x) _x
#define COMPARE_240(_x) _x
#define COMPARE_241(_x) _x
#define COMPARE_242(_x) _x
#define COMPARE_243(_x) _x
#define COMPARE_244(_x) _x
#define COMPARE_245(_x) _x
#define COMPARE_246(_x) _x
#define COMPARE_247(_x) _x
#define COMPARE_248(_x) _x
#define COMPARE_249(_x) _x
#define COMPARE_250(_x) _x
#define COMPARE_251(_x) _x
#define COMPARE_252(_x) _x
#define COMPARE_253(_x) _x
#define COMPARE_254(_x) _x
#define COMPARE_255(_x) _x
#define COMPARE_256(_x) _x

#endif // !MCMT_TOKEN_COMPARE_H
